name: Adminshop
version: 0.0.1
api-version: 1.17
main: de.alpharout.adminshop.AdminShop

softdepend:
  - Citizens

commands:
  adminshop:
    description: Gives you the power to create adminshops.
    aliases: as
    permission: adminshop.command

libraries:
  - com.googlecode.json-simple:json-simple:1.1.1